version: '3.9'

services:
  db:
    container_name: myug-postgres
    image: postgres:14.0-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      myug:
        aliases:
          - db
  pgadmin:
    container_name: myug_pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      myug:
        aliases:
          - pgadmin
  server:
    container_name: myug-server
    build:
      context: ./server
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - '${API_PORT}:3771'
    environment:
      - API_PORT=${API_PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
    volumes:
      - assets:/app/assets
      - etc-letsencrypt:/etc/letsencrypt
    networks:
      myug:
        aliases:
          - server

volumes:
  pgdata:
  pgadmin:
  assets:
  etc-letsencrypt:

networks:
  myug:
    driver: bridge
