version: '3.9'

services:
  db:
    container_name: myug-postgres
    image: postgres:14.0-alpine
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      myug:
        aliases:
          - db
  server:
    container_name: myug-server
    build:
      context: ./server
    depends_on:
    restart: unless-stopped
    ports:
      - '${API_PORT}:3771'
    environment:
      - API_PORT=${API_PORT}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=db
      - MULTER_DEST=${MULTER_DEST}
      - IMAGES_FOLDER=${IMAGES_FOLDER}
    volumes:
      - assets:/app/assets
    networks:
      myug:
        aliases:
          - server

volumes:
  pgdata:
  assets:

networks:
  myug:
    driver: bridge
